### ISSUE TITLE
Weekly summery is not working for me

### ISSUE THREAD

**Issue by ccweerasinghe1994** [anmol098/waka-readme-stats#100]
**Weekly summary is not working**

this is my repo
https://github.com/ccweerasinghe1994

this is the workflow
https://github.com/ccweerasinghe1994/ccweerasinghe1994/blob/master/.github/workflows/blank.yml

![image](https://user-images.githubusercontent.com/40600690/92751069-4ae69400-f3a5-11ea-9b0a-028c7ac9aa14.png)

**Comment by anmol098** [comment]
I can see they are working for you now
