### ISSUE TITLE
BUG I'm having problems

### ISSUE THREAD

**Issue by buster95** [anmol098/waka-readme-stats#105]
**Describe the bug**
stats not committed
![image](https://user-images.githubusercontent.com/15637669/94201479-4926d100-fe79-11ea-96df-dde1350a6b95.png)

**To Reproduce**
This is my yml file
https://github.com/buster95/buster95/blob/master/.github/workflows/update.yml

**Github repository link**
https://github.com/buster95/buster95

**Comment by kinduff** [comment]
Did you add the required permissions for the `GH_TOKEN`?

**Comment by buster95** [comment]
Sorry, that was the problem I needed full repo access
