### ISSUE TITLE
npm WARN vega-lite - You must install peer dependencies yourself.

### ISSUE THREAD

**Issue by wopox1337** [anmol098/waka-readme-stats#106]
**Describe the bug**
Stats can't update.

**To Reproduce**
https://github.com/wopox1337/wopox1337/runs/1168933551?check_suite_focus=true

**Github repository link**
https://github.com/wopox1337/wopox1337/

![image](https://user-images.githubusercontent.com/18553678/94328995-f277df00-ffbf-11ea-8925-5cee8ec0b37e.png)

**Comment by wopox1337** [comment]
@anmol098 ?

**Comment by anmol098** [comment]
@wopox1337 working on this in the mean time you cna set the chart flag to false.. Then it will work as expected..

**Comment by wopox1337** [comment]
Thanks, but now works fine
https://github.com/wopox1337/wopox1337

Should be closed.
