### ISSUE TITLE
Ask about error in my readme

### ISSUE THREAD

**Issue by andre-fajar-n** [anmol098/waka-readme-stats#109]
![image](https://user-images.githubusercontent.com/62334317/95006138-2fc91600-062b-11eb-95b6-3eb1cd248fab.png)
I used waka-readme-stats but occured an error like that. What should I do to solve that? Thank you

**Comment by anmol098** [comment]
We are. Having issue with graphs library please disable that library to make that work.

**Comment by anmol098** [comment]
The bug is fixed can you check now

**Comment by andre-fajar-n** [comment]
It still error
