### ISSUE TITLE
Doesn't work with main branch

### ISSUE THREAD

**Issue by TheKeyblader** [anmol098/waka-readme-stats#118]
**Describe the bug**
https://github.blog/changelog/2020-10-01-the-default-branch-for-newly-created-repositories-is-now-main/
Doesn't work with the new default branch "main"
**Github repository link**
https://github.com/TheKeyblader/TheKeyblader
![](https://i.gyazo.com/65af30fac48d6b6118205a806d06c4d9.png)

**Comment by anmol098** [comment]
Thanks @TheKeyblader for. Pointimg out the... I am working on it and will deploy the fix soon.

**Comment by anmol098** [comment]
#119

**Comment by TheKeyblader** [comment]
Work! 
Thx
