### ISSUE TITLE
Bar chart showing old time for projects with custom rules

### ISSUE THREAD

**Issue by betoma** [anmol098/waka-readme-stats#124]
**Describe the bug**
When a custom rule is used on WakaTime to move files from project A to project B, the time worked on those files as project A is never removed from the bar chart in the readme, despite the time worked on those files moving to project B within wakatime. To make matters worse, this time appears to not roll over from week-to-week after this happens, meaning it's basically permanently added to the bar chart. Even deleting project A on wakatime fails to get rid of it, which makes me suspect it's an issue with the action rather than with wakatime's API.

**To Reproduce**
1. Create a project
2. Work some amount of time on that project, recorded in wakatime
3. Wait for the waka-readme-stats action to run, adding the work done on this project to the readme
4. Use a custom rule in wakatime's settings to move all the time worked on the project to another project
5. (optional) Delete now-empty project on wakatime.
6. Wait for the waka-readme-stats action to run again
7. Observe error in which the time is still shown on the old project
8. Wait at least a week (at which point the readme should not be displaying time over a week old)
9. Observe that all the time worked on the old project is still shown in the readme

**Expected behavior**
Ideally, once the custom rule has fully moved the time from project A to project B, it should be reflected in the next waka-readme-stats run. However, even if that isn't feasible, the work from project A should at least disappear from the readme when it's over a week old.

**Github repository link**
https://github.com/betoma/betoma

**Additional context**
The 41 minutes listed for "code" on my readme was first added back in August, when I first added waka-readme-stats.

**Comment by betoma** [comment]
Update: tried manually removing this 41 minutes from my readme just in case that fixed the issue, but it popped back up the next day. Not surprising, I guess, since that was factoring into the percentages shown for other tasks. Attached is a picture of my projects on Wakatime itself, indicating that the "code" project is no longer present within Wakatime. The only evidence I can find of it is in my github readme, where it still will not leave.
<img width="549" alt="Screenshot 2020-11-16 at 10 37 20" src="https://user-images.githubusercontent.com/32310072/99236973-26b99000-27f8-11eb-937d-0f5c449103ec.png">

**Comment by anmol098** [comment]
We are touching the data given to us by Waka time... We are using only tha data given by the Wakatime apis.
I hope this makes sense... You can go through the api documentation of Waka time.. If you find we are having some bug.. Go ahead and raise a PR with a fix

**Comment by betoma** [comment]
I double-checked the code and ran the API call manually, and this does seem to be a problem on wakatime's end rather than with this action, so I'm closing this issue!
