### ISSUE TITLE
Timeline Chart does not appear when viewed from Github Pages

### ISSUE THREAD

**Issue by subhalingamd** [anmol098/waka-readme-stats#131]
**Describe the bug**
When Github Pages is activated and `README.md` is viewed from the personal website (e.g. `username.github.io/username/`), the timeline chart does not load. 

**To Reproduce**
1. Go to https://subhalingamd.github.io/subhalingamd/
2. Scroll down to *Timeline*
4. See the error (image does not load)

**Expected behavior**
The Timeline Chart should load as it does in https://github.com/subhalingamd

**Github repository link**
https://github.com/subhalingamd/subhalingamd

**Comment by subhalingamd** [comment]
Changing the image URL from https://github.com/subhalingamd/subhalingamd/blob/master/charts/bar_graph.png to https://raw.githubusercontent.com/subhalingamd/subhalingamd/master/charts/bar_graph.png seems to fix the issue.

**Comment by anmol098** [comment]
Ya it should fix the issue... Go ahead and open a PR
With the fix.. If it's a fix.. The. Will definitely merge that... 👍

**Comment by subhalingamd** [comment]
> Changing the image URL from https://github.com/subhalingamd/subhalingamd/blob/master/charts/bar_graph.png to https://raw.githubusercontent.com/subhalingamd/subhalingamd/master/charts/bar_graph.png seems to fix the issue.

![Screenshot 2020-11-23 at 09 14 27](https://user-images.githubusercontent.com/48081462/99927727-6dfdce80-2d6c-11eb-8263-c9eccb8c9aeb.png)

**Comment by anmol098** [comment]
#132 #132
