### ISSUE TITLE
BUG - Waka Readme Stats GitHub Action Failed

### ISSUE THREAD

**Issue by henryboisdequin** [anmol098/waka-readme-stats#135]
**Describe the bug**
The action failed and didn't update my readme.

**To Reproduce**
Steps to reproduce the behaviour:
It should happen to everyone who uses waka readme stats if it's just my problem, you could copy my workflow .yml file and try it: https://github.com/henryboisdequin/henryboisdequin.

**Expected behaviour**
I expected the action to be performed successfully.

**Additional context**
<img width="1438" alt="Screenshot 2020-12-02 at 06 19 06" src="https://user-images.githubusercontent.com/65845077/100814001-ae450700-3466-11eb-8e44-95351122ea80.png">

**Comment by anmol098** [comment]
Just saw your profile the last action run was successful and the readme was updated as expected
