### ISSUE TITLE
Authenticating with the GITHUB_TOKEN

### ISSUE THREAD

**Issue by ming-tsai** [anmol098/waka-readme-stats#14]
We could use `GITHUB_TOKEN` as an environment variable, so the user doesn't have to generate a token when they are configuring the scheduled job, see more documentation on the official page.
- [Authenticating with the `GITHUB_TOKEN`](https://docs.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token#about-the-github_token-secret)
- [Permissions for the `GITHUB_TOKEN`](https://docs.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token#permissions-for-the-github_token)

I can work on this change if it's ok with you

**Comment by anmol098** [comment]
@ming-tsai we can use this... But as far as I know that this token is valid on the repository on which action is being run only.....
But as are functionality we have many other dev metrics which require reading all repository of user to show the metrics....
PS-we are using token to get the commit timestamp and the [Statistics ](https://developer.github.com/v3/repos/statistics/) api to read the number of additions and subtraction.

**Comment by ming-tsai** [comment]
> @ming-tsai we can use this... But as far as I know that this token is valid on the repository on which action is being run only.....
> But as are functionality we have many other dev metrics which require reading all repository of user to show the metrics....
> PS-we are using token to get the commit timestamp and the [Statistics ](https://developer.github.com/v3/repos/statistics/) api to read the number of additions and subtraction.

Ok, I thought that it has permission to read private repositories
