### ISSUE TITLE
Unauthorised and forceful star

### ISSUE THREAD

**Issue by aravindvnair99** [anmol098/waka-readme-stats#161]
Hey @anmol098!

Just wanted to point out something and discuss it...

Although I appreciate your efforts and time, I don't think it's right to simply star this repository using the code. Either leave it to your userbase to star if they wish to which definitely people will if they are interested, else, the least you can do is mention in the README that you are doing this so that users are aware you are doing such a thing.

Just to be clear, although I am happy to star, forcing to star is simply not right in my opinion.

https://github.com/anmol098/waka-readme-stats/blob/03935543d0f25ed9cdb6ae8678cb0fcbfd16b428/main.py#L462-L463

https://github.com/anmol098/waka-readme-stats/blob/03935543d0f25ed9cdb6ae8678cb0fcbfd16b428/main.py#L498

**Comment by aaditkamat** [comment]
+1 @aravindvnair99! @anmol098, since you've already mentioned in the README to leave a star if users like the project, I think we should remove the function that does it automatically from the GitHub API.
