### ISSUE TITLE
Profile Views Not Working

### ISSUE THREAD

**Issue by IronicNinja** [anmol098/waka-readme-stats#163]
**Describe the bug**
On my profile, my profile views appears as 0, even though there's no way that's the case. Just a week ago, my profile views was around 170-180, dropped to around 18 in subsequent days, and now is at 0.
![image](https://user-images.githubusercontent.com/37968721/105070759-bde9d080-5a51-11eb-9591-2acf60e95acb.png)

**To Reproduce**
For reference, here's my profile repo: https://github.com/IronicNinja/IronicNinja

**Comment by subhalingamd** [comment]
According to line 89 in [main.py](https://github.com/anmol098/waka-readme-stats/blob/1431621a825acf6d266f1db27ccafcf8bfb6e89d/main.py), the Profile View badge shows the traffic for **each week**

**Comment by IronicNinja** [comment]
> @IronicNinja According to line 89 in [main.py](https://github.com/anmol098/waka-readme-stats/blob/1431621a825acf6d266f1db27ccafcf8bfb6e89d/main.py#L89), the Profile View badge shows the traffic for **each week**

Oh ok thank you. Is there a way to change that from profile views per week to something like per year?

**Comment by subhalingamd** [comment]
> > @IronicNinja According to line 89 in [main.py](https://github.com/anmol098/waka-readme-stats/blob/1431621a825acf6d266f1db27ccafcf8bfb6e89d/main.py#L89), the Profile View badge shows the traffic for **each week**
> 
> Oh ok thank you. Is there a way to change that from profile views per week to something like per year?

According to [this](https://docs.github.com/en/rest/reference/repos#traffic) doc, **`per`** must be one of: `day`, `week`. So I guess `year` is not possible from the API.

However, you might find [this](https://visitor-badge.laobi.icu) one helpful.

**Comment by IronicNinja** [comment]
> > > @IronicNinja According to line 89 in [main.py](https://github.com/anmol098/waka-readme-stats/blob/1431621a825acf6d266f1db27ccafcf8bfb6e89d/main.py#L89), the Profile View badge shows the traffic for **each week**
> > 
> > 
> > Oh ok thank you. Is there a way to change that from profile views per week to something like per year?
> 
> According to [this](https://docs.github.com/en/rest/reference/repos#traffic) doc, **`per`** must be one of: `day`, `week`. So I guess `year` is not possible from the API.
> 
> However, you might find [this](https://visitor-badge.laobi.icu) one helpful.

Got it, thank you so much.
