### ISSUE TITLE
Docker Build Failed due to OpenCv-Python 4.2

### ISSUE THREAD

**Issue by faatehsultan** [anmol098/waka-readme-stats#164]
Workflow fails every time due to some error.

Please see the [workflow here](https://github.com/faatehsultan/faatehsultan/runs/1756731041) and resolve this

thank you

**Comment by aravindvnair99** [comment]
@faatehsultan Change your workflow to use `anmol098/waka-readme-stats@master`. v3 was released long ago.

**Comment by faatehsultan** [comment]
Thank you @aravindvnair99 my issue resolved. I am closing this issue!
