### ISSUE TITLE
Profile views not showing up properly

### ISSUE THREAD

**Issue by tejasag** [anmol098/waka-readme-stats#177]
**Describe the bug**
I have the profile views enabled but the tag does not show up properly because of it being directly under an HTML tag inside a details tag (the starting comment) in the markdown file.

![image](https://user-images.githubusercontent.com/67542663/111072950-cf57d200-8502-11eb-9adc-bdb49c778098.png)

**Expected behavior**
It should add the stats leaving one line after the start comment 

**Github repository link**
My readme: https://github.com/tejasag/tejasag
My workflow: https://github.com/tejasag/tejasag/blob/main/.github/workflows/main.yml

**Additional context**
Demonstration: 
what is happening:
```md
<details>
<summary> stats </summary>
<!-- START_SECTION:waka -->
![example](https://picsum.photos/20/20)
</details>
```
<details>
<summary> stats </summary>

![example](https://picsum.photos/20/20)
</details>

What should happen:
```md
<details>
<summary> stats </summary>
<!-- START_SECTION:waka -->

![example](https://picsum.photos/20/20)
</details>
```
<details>
<summary> stats </summary>

![example](https://picsum.photos/20/20)
</details>

**Comment by subhalingamd** [comment]
@tejasag Why not use the line break before the comment? 
```
<details>
<summary> stats </summary>

<!-- START_SECTION:waka -->
![example](https://picsum.photos/20/20)
</details>
```

gets rendered as:

<details>
<summary> stats </summary>


![example](https://picsum.photos/20/20)
</details>
