### ISSUE TITLE
Bug: File "/main.py", line 312, in <module>

### ISSUE THREAD

**Issue by TGTGamer** [anmol098/waka-readme-stats#19]
Error when running.

```
Traceback (most recent call last):
  File "/main.py", line 312, in <module>
    repo.update_file(path=contents.path, message='Updated with Dev Metrics',
  File "/usr/local/lib/python3.8/site-packages/github/Repository.py", line 2098, in update_file
    headers, data = self._requester.requestJsonAndCheck(
  File "/usr/local/lib/python3.8/site-packages/github/Requester.py", line 317, in requestJsonAndCheck
    return self.__check(
  File "/usr/local/lib/python3.8/site-packages/github/Requester.py", line 342, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.GithubException: 409 {"message": "README.md does not match 6bbbd746ff8ea3babb6a49e551ccc2858e18f20c", "documentation_url": "https://developer.github.com/v3/repos/contents/#create-or-update-a-file"}
```

**Comment by anmol098** [comment]
@TGTGamer as I can see in your logs it's running fine.
It failed because its running on infinite loop. And may be its because hitting concurrent request to the github apis and it might fail due to heavy request. 
Please change the yml file and change it to schedule only....

**Comment by anmol098** [comment]
@TGTGamer please see to the Pull request which I have created to your repository.

**Comment by pr2tik1** [comment]
Traceback (most recent call last):
  File "/main.py", line 302, in <module>
    repo = g.get_repo(f"{user}/{user}")
  File "/usr/local/lib/python3.8/site-packages/github/MainClass.py", line 324, in get_repo
    headers, data = self.__requester.requestJsonAndCheck(
  File "/usr/local/lib/python3.8/site-packages/github/Requester.py", line 317, in requestJsonAndCheck
    return self.__check(
  File "/usr/local/lib/python3.8/site-packages/github/Requester.py", line 342, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.BadCredentialsException: 401 {"message": "Bad credentials", "documentation_url": "https://developer.github.com/v3"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/main.py", line 303, in <module>
    except GithubException:
NameError: name 'GithubException' is not defined


## Same error while running on schedule run.

**Comment by anmol098** [comment]
@pr2tik1 did you add the github personal access token and Wakatime time to the repository secret?

**Comment by pr2tik1** [comment]
> @pr2tik1 did you add the github personal access token and Wakatime time to the repository secret?

@anmol098  Yes, I did, I have checked and updated it again. However, It shows,

/usr/bin/docker run --name c201132c22c546914474b8847645b9b082e2_7653e1 --label 87c201 --workdir /github/workspace --rm -e INPUT_WAKATIME_API_KEY -e INPUT_GH_TOKEN -e INPUT_SHOW_PROJECTS -e INPUT_SHOW_LINES_OF_CODE -e INPUT_USERNAME -e INPUT_SHOW_OS -e INPUT_SHOW_EDITORS -e INPUT_SHOW_TIMEZONE -e INPUT_SHOW_COMMIT -e INPUT_SHOW_LANGUAGE -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/pr2tik1/pr2tik1":"/github/workspace" 87c201:132c22c546914474b8847645b9b082e2
Traceback (most recent call last):
  File "/main.py", line 302, in <module>
    repo = g.get_repo(f"{user}/{user}")
  File "/usr/local/lib/python3.8/site-packages/github/MainClass.py", line 324, in get_repo
    headers, data = self.__requester.requestJsonAndCheck(
  File "/usr/local/lib/python3.8/site-packages/github/Requester.py", line 317, in requestJsonAndCheck
    return self.__check(
  File "/usr/local/lib/python3.8/site-packages/github/Requester.py", line 342, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.BadCredentialsException: 401 {"message": "Bad credentials", "documentation_url": "https://developer.github.com/v3"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/main.py", line 303, in <module>
    except GithubException:
NameError: name 'GithubException' is not defined

**Comment by anmol098** [comment]
I have seen your log files on your profile it's not taking the Wakatime api key and github token to the environment vairble but it has taken the feature flags as the input... I request to please double Check the repository secret.. Or if possible please share the screnshot of the repository secret screen.....

**Comment by pr2tik1** [comment]
> I have seen your log files on your profile it's not taking the Wakatime api key and github token to the environment vairble but it has taken the feature flags as the input... I request to please double Check the repository secret.. Or if possible please share the screnshot of the repository secret screen.....

I have edited the secrets and now it's working, the problem was my side. My bad, thank-you!! @anmol098
