### ISSUE TITLE
main.py traceback

### ISSUE THREAD

**Issue by alexanderniebuhr** [anmol098/waka-readme-stats#190]
sorry it is broken since 2d, commit c59d497f95bb9e5c10bb90d5a6597fb5cb223508, works fine.. can't give more insights, since I am changing to my custom action .. still think it might be good to report for you

```
Traceback (most recent call last):
23
  File "/main.py", line 489, in <module>
24
    username = user_data["data"]["viewer"]["login"]
25
KeyError: 'data'
26
Exception Occurred 'data'
```

**Comment by PoseidonCoder** [comment]
```py
Traceback (most recent call last):
Exception Occurred 'data'
  File "/main.py", line 489, in <module>
    username = user_data["data"]["viewer"]["login"]
KeyError: 'data'
```

I also had the same issue.

**Comment by PoseidonCoder** [comment]
I solved it! For me, the issue was that I hadn't given the access token enough permissions. My access token required the user scope.
![image](https://user-images.githubusercontent.com/34260118/115431054-bdc8b080-a1b9-11eb-991e-580eef138d75.png)

**Comment by alexanderniebuhr** [comment]
This is new than..

**Comment by biningo** [comment]
> ## I solved it!
> For me, the issue was that I hadn't given the access token enough permissions. My access token required the user scope.
> ![image](https://user-images.githubusercontent.com/34260118/115431054-bdc8b080-a1b9-11eb-991e-580eef138d75.png)

Haha, yeah....

**Comment by aravindvnair99** [comment]
> This is new than..

@alexanderniebuhr It isn't new. It's mentioned in the README itself (3rd point):

![image](https://user-images.githubusercontent.com/22199259/116467181-0acd1680-a88d-11eb-9ddb-f81c1c28ce6b.png)

You can close this issue as it's not a valid issue.
