### ISSUE TITLE
Add flag to show/hide daily day of the week commit stats

### ISSUE THREAD

**Issue by Galarzaa90** [anmol098/waka-readme-stats#21]
I see that commit stats now include days of the week.

I think it would be nice to have a flag to hide this section (without hiding time of the day stats) and maybe the other way around.

This way, you can keep the readme's content shorter if desired, and only include the sections you want.

**Comment by anmol098** [comment]
Ok thanks for the suggestion.. Will fix that soon in next update...

**Comment by anmol098** [comment]
@Galarzaa90 #26 fixed this issue you can check

**Comment by Galarzaa90** [comment]
Very nice 💯
