### ISSUE TITLE
The letter case of the word "GitHub" in `translation.json` is wrong

### ISSUE THREAD

**Issue by CSY54** [anmol098/waka-readme-stats#214]
**Is your feature request related to a problem? Please describe.**
Right before the translation process started, the letter case of the word "GitHub" is correct (capital G and capital H).
However, from the first version of [`translation.json`](https://github.com/anmol098/waka-readme-stats/commit/b4da99e6715e884109eba2311a71c7f4e6424fc6#diff-f1724ac129587c875a669bffba57c9b48c3ffb3244c23cc7826f8acaf5e4548a), the letter case is wrong until now (capital G but small h).

**Describe the solution you'd like**
Correct all of the "Github" into "GitHub" in `translation.json`.

**Comment by anmol098** [comment]
merged closing this
