### ISSUE TITLE
Problem of data display 

### ISSUE THREAD

**Issue by branlito** [anmol098/waka-readme-stats#224]
Hey guys, 

Can I know why there is only my langages hours that are displayed on my github readme ?

I have a lot of data : 
https://wakatime.com/api/v1/users/branlito/stats/last_7_days

I have also set some flags to "True" like SHOW_OS: "True" but it is never displayed.
My run doesn't drop erros so I don't know.

Here is my .yml file : 
`name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics Wakatime
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LANGUAGE: "True"
          SHOW_OS: "True"
          SHOW_TIMEZONE: "False"
          SHOW_EDITORS: "True"
          SHOW_LOC_CHART: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_SHORT_INFO: "False"
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_PROJECTS: "False"
          SHOW_LINES_OF_CODE: "True"`

Please help me :)

**Comment by anmol098** [comment]
@branlito  as i can see on your profile the OS data is displaying. so closing this issue
