### ISSUE TITLE
BUG: Docker build failed with exit code 1

### ISSUE THREAD

**Issue by behroozazarkhalili** [anmol098/waka-readme-stats#226]
**Describe the bug**
As of this morning, I have been receiving the following error when running the waka-readme-stats action workflow.

### Update this repo's README
Docker build failed with exit code 1

### Update this repo's README
Docker build failed with exit code 1, back off 3.7 seconds before retry.

### Update this repo's README
Docker build failed with exit code 1, back off 2.329 seconds before retry.

my .yaml file for this action can be found [here](https://github.com/behroozazarkhalili/behroozazarkhalili/blob/main/.github/workflows/Waka-Readme.yml):
<br class="Apple-interchange-newline">

**Comment by mheob** [comment]
Some additional information of my action log:

```
  ...

  Step 12/13 : RUN npm i -g agentkeepalive npm@latest vega vega-lite vega-cli canvas
   ---> Running in fa925fb40a52
  npm ERR! code 1
  npm ERR! path /usr/lib/node_modules/canvas
  npm ERR! command failed
  npm ERR! command sh -c node-pre-gyp install --fallback-to-build
  npm ERR! Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/lib/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/usr/lib/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v88' (1)
  npm ERR! node-pre-gyp info it worked if it ends with ok
  npm ERR! node-pre-gyp info using node-pre-gyp@1.0.5
  npm ERR! node-pre-gyp info using node@15.14.0 | linux | x64
  npm ERR! node-pre-gyp info check checked for "/usr/lib/node_modules/canvas/build/Release/canvas.node" (not found)
  npm ERR! node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v88-linux-glibc-x64.tar.gz
  npm ERR! node-pre-gyp ERR! install response status 403 Forbidden on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v88-linux-glibc-x64.tar.gz 
  npm ERR! node-pre-gyp WARN Pre-built binaries not installable for canvas@2.8.0 and node@15.14.0 (node-v88 ABI, glibc) (falling back to source compile with node-gyp) 
  npm ERR! node-pre-gyp WARN Hit error response status 403 Forbidden on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v88-linux-glibc-x64.tar.gz 
  npm ERR! gyp info it worked if it ends with ok
  npm ERR! gyp info using node-gyp@7.1.2
  npm ERR! gyp info using node@15.14.0 | linux | x64
  npm ERR! gyp info ok 
  npm ERR! gyp info it worked if it ends with ok
  npm ERR! gyp info using node-gyp@7.1.2
  npm ERR! gyp info using node@15.14.0 | linux | x64
  npm ERR! gyp info find Python using Python version 3.8.10 found at "/usr/local/bin/python3"
  npm ERR! gyp http GET https://nodejs.org/download/release/v15.14.0/node-v15.14.0-headers.tar.gz
  npm ERR! gyp http 200 https://nodejs.org/download/release/v15.14.0/node-v15.14.0-headers.tar.gz
  npm ERR! gyp http GET https://nodejs.org/download/release/v15.14.0/SHASUMS256.txt
  npm ERR! gyp http 200 https://nodejs.org/download/release/v15.14.0/SHASUMS256.txt
  npm ERR! gyp info spawn /usr/local/bin/python3
  npm ERR! gyp info spawn args [
  npm ERR! gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
  npm ERR! gyp info spawn args   'binding.gyp',
  npm ERR! gyp info spawn args   '-f',
  npm ERR! gyp info spawn args   'make',
  npm ERR! gyp info spawn args   '-I',
  npm ERR! gyp info spawn args   '/usr/lib/node_modules/canvas/build/config.gypi',
  npm ERR! gyp info spawn args   '-I',
  npm ERR! gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
  npm ERR! gyp info spawn args   '-I',
  npm ERR! gyp info spawn args   '/root/.cache/node-gyp/15.14.0/include/node/common.gypi',
  npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
  npm ERR! gyp info spawn args   '-Dvisibility=default',
  npm ERR! gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/15.14.0',
  npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
  npm ERR! gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/15.14.0/<(target_arch)/node.lib',
  npm ERR! gyp info spawn args   '-Dmodule_root_dir=/usr/lib/node_modules/canvas',
  npm ERR! gyp info spawn args   '-Dnode_engine=v8',
  npm ERR! gyp info spawn args   '--depth=.',
  npm ERR! gyp info spawn args   '--no-parallel',
  npm ERR! gyp info spawn args   '--generator-output',
  npm ERR! gyp info spawn args   'build',
  npm ERR! gyp info spawn args   '-Goutput_dir=.'
  npm ERR! gyp info spawn args ]
  npm ERR! Package pangocairo was not found in the pkg-config search path.
  npm ERR! Perhaps you should add the directory containing `pangocairo.pc'
  npm ERR! to the PKG_CONFIG_PATH environment variable
  npm ERR! No package 'pangocairo' found
  npm ERR! gyp: Call to 'pkg-config pangocairo --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
  npm ERR! gyp ERR! configure error 
  npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
  npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
  npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:369:20)
  npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
  npm ERR! gyp ERR! System Linux 5.8.0-1041-azure
  npm ERR! gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/usr/lib/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/usr/lib/node_modules/canvas/build/Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v88"
  npm ERR! gyp ERR! cwd /usr/lib/node_modules/canvas
  npm ERR! gyp ERR! node -v v15.14.0
  npm ERR! gyp ERR! node-gyp -v v7.1.2
  npm ERR! gyp ERR! not ok 
  npm ERR! node-pre-gyp ERR! build error 
  npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/lib/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/usr/lib/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v88' (1)
  npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/canvas/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
  npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:369:20)
  npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1067:16)
  npm ERR! node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
  npm ERR! node-pre-gyp ERR! System Linux 5.8.0-1041-azure
  npm ERR! node-pre-gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/canvas/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
  npm ERR! node-pre-gyp ERR! cwd /usr/lib/node_modules/canvas
  npm ERR! node-pre-gyp ERR! node -v v15.14.0
  npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.5
  npm ERR! node-pre-gyp ERR! not ok
  
  npm ERR! A complete log of this run can be found in:
  npm ERR!     /root/.npm/_logs/2021-09-21T05_06_29_239Z-debug.log
  The command '/bin/sh -c npm i -g agentkeepalive npm@latest vega vega-lite vega-cli canvas' returned a non-zero code: 1
```

**Comment by behroozazarkhalili** [comment]
> Some additional information of [my action log](https://github.com/mheob/mheob/runs/3659505988):
> 
> ```
>   ...
> 
>   Step 12/13 : RUN npm i -g agentkeepalive npm@latest vega vega-lite vega-cli canvas
>    ---> Running in fa925fb40a52
>   npm ERR! code 1
>   npm ERR! path /usr/lib/node_modules/canvas
>   npm ERR! command failed
>   npm ERR! command sh -c node-pre-gyp install --fallback-to-build
>   npm ERR! Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/lib/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/usr/lib/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v88' (1)
>   npm ERR! node-pre-gyp info it worked if it ends with ok
>   npm ERR! node-pre-gyp info using node-pre-gyp@1.0.5
>   npm ERR! node-pre-gyp info using node@15.14.0 | linux | x64
>   npm ERR! node-pre-gyp info check checked for "/usr/lib/node_modules/canvas/build/Release/canvas.node" (not found)
>   npm ERR! node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v88-linux-glibc-x64.tar.gz
>   npm ERR! node-pre-gyp ERR! install response status 403 Forbidden on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v88-linux-glibc-x64.tar.gz 
>   npm ERR! node-pre-gyp WARN Pre-built binaries not installable for canvas@2.8.0 and node@15.14.0 (node-v88 ABI, glibc) (falling back to source compile with node-gyp) 
>   npm ERR! node-pre-gyp WARN Hit error response status 403 Forbidden on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v88-linux-glibc-x64.tar.gz 
>   npm ERR! gyp info it worked if it ends with ok
>   npm ERR! gyp info using node-gyp@7.1.2
>   npm ERR! gyp info using node@15.14.0 | linux | x64
>   npm ERR! gyp info ok 
>   npm ERR! gyp info it worked if it ends with ok
>   npm ERR! gyp info using node-gyp@7.1.2
>   npm ERR! gyp info using node@15.14.0 | linux | x64
>   npm ERR! gyp info find Python using Python version 3.8.10 found at "/usr/local/bin/python3"
>   npm ERR! gyp http GET https://nodejs.org/download/release/v15.14.0/node-v15.14.0-headers.tar.gz
>   npm ERR! gyp http 200 https://nodejs.org/download/release/v15.14.0/node-v15.14.0-headers.tar.gz
>   npm ERR! gyp http GET https://nodejs.org/download/release/v15.14.0/SHASUMS256.txt
>   npm ERR! gyp http 200 https://nodejs.org/download/release/v15.14.0/SHASUMS256.txt
>   npm ERR! gyp info spawn /usr/local/bin/python3
>   npm ERR! gyp info spawn args [
>   npm ERR! gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
>   npm ERR! gyp info spawn args   'binding.gyp',
>   npm ERR! gyp info spawn args   '-f',
>   npm ERR! gyp info spawn args   'make',
>   npm ERR! gyp info spawn args   '-I',
>   npm ERR! gyp info spawn args   '/usr/lib/node_modules/canvas/build/config.gypi',
>   npm ERR! gyp info spawn args   '-I',
>   npm ERR! gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
>   npm ERR! gyp info spawn args   '-I',
>   npm ERR! gyp info spawn args   '/root/.cache/node-gyp/15.14.0/include/node/common.gypi',
>   npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
>   npm ERR! gyp info spawn args   '-Dvisibility=default',
>   npm ERR! gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/15.14.0',
>   npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
>   npm ERR! gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/15.14.0/<(target_arch)/node.lib',
>   npm ERR! gyp info spawn args   '-Dmodule_root_dir=/usr/lib/node_modules/canvas',
>   npm ERR! gyp info spawn args   '-Dnode_engine=v8',
>   npm ERR! gyp info spawn args   '--depth=.',
>   npm ERR! gyp info spawn args   '--no-parallel',
>   npm ERR! gyp info spawn args   '--generator-output',
>   npm ERR! gyp info spawn args   'build',
>   npm ERR! gyp info spawn args   '-Goutput_dir=.'
>   npm ERR! gyp info spawn args ]
>   npm ERR! Package pangocairo was not found in the pkg-config search path.
>   npm ERR! Perhaps you should add the directory containing `pangocairo.pc'
>   npm ERR! to the PKG_CONFIG_PATH environment variable
>   npm ERR! No package 'pangocairo' found
>   npm ERR! gyp: Call to 'pkg-config pangocairo --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
>   npm ERR! gyp ERR! configure error 
>   npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
>   npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
>   npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:369:20)
>   npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
>   npm ERR! gyp ERR! System Linux 5.8.0-1041-azure
>   npm ERR! gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/usr/lib/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/usr/lib/node_modules/canvas/build/Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v88"
>   npm ERR! gyp ERR! cwd /usr/lib/node_modules/canvas
>   npm ERR! gyp ERR! node -v v15.14.0
>   npm ERR! gyp ERR! node-gyp -v v7.1.2
>   npm ERR! gyp ERR! not ok 
>   npm ERR! node-pre-gyp ERR! build error 
>   npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/lib/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/usr/lib/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v88' (1)
>   npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/canvas/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
>   npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:369:20)
>   npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1067:16)
>   npm ERR! node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
>   npm ERR! node-pre-gyp ERR! System Linux 5.8.0-1041-azure
>   npm ERR! node-pre-gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/canvas/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
>   npm ERR! node-pre-gyp ERR! cwd /usr/lib/node_modules/canvas
>   npm ERR! node-pre-gyp ERR! node -v v15.14.0
>   npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.5
>   npm ERR! node-pre-gyp ERR! not ok
>   
>   npm ERR! A complete log of this run can be found in:
>   npm ERR!     /root/.npm/_logs/2021-09-21T05_06_29_239Z-debug.log
>   The command '/bin/sh -c npm i -g agentkeepalive npm@latest vega vega-lite vega-cli canvas' returned a non-zero code: 1
> ```

Do you have any idea as to what the problem is?

**Comment by mheob** [comment]
It seems that the node package `canvas` can't be installed.

```
npm ERR! node-pre-gyp ERR! install response status 403 Forbidden on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v88-linux-glibc-x64.tar.gz 
```

But I don't know why that is. A manual download works fine. I don't have the time to deal with it now. Maybe later. Hopefully @anmol098 can help faster.

**Comment by pacholoamit** [comment]
Yeah, same here. Facing the same issue

**Comment by MasterCoder1234567890** [comment]
Exactly I AM Facing The SAME ISSUE

**Comment by MasterCoder1234567890** [comment]
See My This On My [action log:](https://github.com/MasterCoder1234567890/MasterCoder1234567890/runs/3661617687?check_suite_focus=true)

**Comment by MasterCoder1234567890** [comment]
This Is the Error Coming On My [Action Log](https://github.com/MasterCoder1234567890/MasterCoder1234567890/runs/3661617687?check_suite_focus=true)

 Step 12/13 : RUN npm i -g agentkeepalive npm@latest vega vega-lite vega-cli canvas
   ---> Running in 4422a62aabe3
  npm ERR! code 1
  npm ERR! path /usr/lib/node_modules/canvas
  npm ERR! command failed
  npm ERR! command sh -c node-pre-gyp install --fallback-to-build
  npm ERR! Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/lib/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/usr/lib/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v88' (1)
  npm ERR! node-pre-gyp info it worked if it ends with ok
  npm ERR! node-pre-gyp info using node-pre-gyp@1.0.5
  npm ERR! node-pre-gyp info using node@15.14.0 | linux | x64
  npm ERR! node-pre-gyp info check checked for "/usr/lib/node_modules/canvas/build/Release/canvas.node" (not found)
  npm ERR! node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v88-linux-glibc-x64.tar.gz
  npm ERR! node-pre-gyp ERR! install response status 403 Forbidden on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v88-linux-glibc-x64.tar.gz 
  npm ERR! node-pre-gyp WARN Pre-built binaries not installable for canvas@2.8.0 and node@15.14.0 (node-v88 ABI, glibc) (falling back to source compile with node-gyp) 
  npm ERR! node-pre-gyp WARN Hit error response status 403 Forbidden on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v88-linux-glibc-x64.tar.gz 
  npm ERR! gyp info it worked if it ends with ok
  npm ERR! gyp info using node-gyp@7.1.2
  npm ERR! gyp info using node@15.14.0 | linux | x64
  npm ERR! gyp info ok 
  npm ERR! gyp info it worked if it ends with ok
  npm ERR! gyp info using node-gyp@7.1.2
  npm ERR! gyp info using node@15.14.0 | linux | x64
  npm ERR! gyp info find Python using Python version 3.8.10 found at "/usr/local/bin/python3"
  npm ERR! gyp http GET https://nodejs.org/download/release/v15.14.0/node-v15.14.0-headers.tar.gz
  npm ERR! gyp http 200 https://nodejs.org/download/release/v15.14.0/node-v15.14.0-headers.tar.gz
  npm ERR! gyp http GET https://nodejs.org/download/release/v15.14.0/SHASUMS256.txt
  npm ERR! gyp http 200 https://nodejs.org/download/release/v15.14.0/SHASUMS256.txt
  npm ERR! gyp info spawn /usr/local/bin/python3
  npm ERR! gyp info spawn args [
  npm ERR! gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
  npm ERR! gyp info spawn args   'binding.gyp',
  npm ERR! gyp info spawn args   '-f',
  npm ERR! gyp info spawn args   'make',
  npm ERR! gyp info spawn args   '-I',
  npm ERR! gyp info spawn args   '/usr/lib/node_modules/canvas/build/config.gypi',
  npm ERR! gyp info spawn args   '-I',
  npm ERR! gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
  npm ERR! gyp info spawn args   '-I',
  npm ERR! gyp info spawn args   '/root/.cache/node-gyp/15.14.0/include/node/common.gypi',
  npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
  npm ERR! gyp info spawn args   '-Dvisibility=default',
  npm ERR! gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/15.14.0',
  npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
  npm ERR! gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/15.14.0/<(target_arch)/node.lib',
  npm ERR! gyp info spawn args   '-Dmodule_root_dir=/usr/lib/node_modules/canvas',
  npm ERR! gyp info spawn args   '-Dnode_engine=v8',
  npm ERR! gyp info spawn args   '--depth=.',
  npm ERR! gyp info spawn args   '--no-parallel',
  npm ERR! gyp info spawn args   '--generator-output',
  npm ERR! gyp info spawn args   'build',
  npm ERR! gyp info spawn args   '-Goutput_dir=.'
  npm ERR! gyp info spawn args ]
  npm ERR! Package pangocairo was not found in the pkg-config search path.
  npm ERR! Perhaps you should add the directory containing `pangocairo.pc'
  npm ERR! to the PKG_CONFIG_PATH environment variable
  npm ERR! No package 'pangocairo' found
  npm ERR! gyp: Call to 'pkg-config pangocairo --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
  npm ERR! gyp ERR! configure error 
  npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
  npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
  npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:369:20)
  npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
  npm ERR! gyp ERR! System Linux 5.8.0-1041-azure
  npm ERR! gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/usr/lib/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/usr/lib/node_modules/canvas/build/Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v88"
  npm ERR! gyp ERR! cwd /usr/lib/node_modules/canvas
  npm ERR! gyp ERR! node -v v15.14.0
  npm ERR! gyp ERR! node-gyp -v v7.1.2
  npm ERR! gyp ERR! not ok 
  npm ERR! node-pre-gyp ERR! build error 
  npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/lib/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/usr/lib/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v88' (1)
  npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/canvas/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
  npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:369:20)
  npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1067:16)
  npm ERR! node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
  npm ERR! node-pre-gyp ERR! System Linux 5.8.0-1041-azure
  npm ERR! node-pre-gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/canvas/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
  npm ERR! node-pre-gyp ERR! cwd /usr/lib/node_modules/canvas
  npm ERR! node-pre-gyp ERR! node -v v15.14.0
  npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.5
  npm ERR! node-pre-gyp ERR! not ok
  
  npm ERR! A complete log of this run can be found in:
  npm ERR!     /root/.npm/_logs/2021-09-21T09_41_48_652Z-debug.log
  The command '/bin/sh -c npm i -g agentkeepalive npm@latest vega vega-lite vega-cli canvas' returned a non-zero code: 1
  
  Warning: Docker build failed with exit code 1, back off 7.203 seconds before retry.
  /usr/bin/docker build -t 48c179:2e6ff6b929284be9a96dc8467d0a26f4 -f "/home/runner/work/_actions/anmol098/waka-readme-stats/master/Dockerfile" "/home/runner/work/_actions/anmol098/waka-readme-stats/master"
  Sending build context to Docker daemon  180.2kB

**Comment by Saicharan67** [comment]
Same here too

**Comment by rmaafs** [comment]
Same here. But I re-run the job and It works fine!

**Comment by MasterCoder1234567890** [comment]
Please Tell The Solution For This Issue.....
I Am Unable to figure it out

**Comment by fbuireu** [comment]
> Please Tell The Solution For This Issue.....
> I Am Unable to figure it out

Just re-run the GitHub action, it has been fixed. The issue has been solved since, as it has been debugged in https://github.com/anmol098/waka-readme-stats/issues/226#issuecomment-923650104 the issue was outside the scope of this repo.

If you are still having problems, it may be that the cause is different than the one discussed in this thread.

**Comment by anmol098** [comment]
There was some issue with the canvas NPM package and it is working fine now.
