### ISSUE TITLE
BUG : Build Error causing stats to fail readme render

### ISSUE THREAD

**Issue by DionneNoellaBarretto** [anmol098/waka-readme-stats#236]
**Describe the bug** / **To Reproduce**
Running into run time errors causing line 515 to never execute because of the exception "Cannot find the Locale choosing default to english" match resulting in waka stats not updating in user's readme file.. Seems like a widespread user problem..

Wasn't able to follow through entirely but I wonder if some recent commits in https://github.com/PyGithub/PyGithub/commits/master repo caused this problem.. ?

**Expected behavior**
Stats update in readme

**Github repository link**
https://github.com/DionneNoellaBarretto/DionneNoellaBarretto

**Additional context**

May be related to https://github.com/anmol098/waka-readme-stats/issues/231 

Run Time Build Error:
`/usr/bin/docker run --name f8842045d1aeaba05d43d99d460f8304578bf5_f6bf07 --label f88420 --workdir /github/workspace --rm -e INPUT_WAKATIME_API_KEY -e INPUT_GH_TOKEN -e INPUT_SHOW_LINES_OF_CODE -e INPUT_SHOW_TIMEZONE -e INPUT_SHOW_EDITORS -e INPUT_SHOW_LANGUAGE_PER_REPO -e INPUT_SHOW_OS -e INPUT_SHOW_PROJECTS -e INPUT_SHOW_COMMIT -e INPUT_SHOW_DAYS_OF_WEEK -e INPUT_SHOW_LOC_CHART -e INPUT_SHOW_LANGUAGE -e INPUT_LOCALE -e INPUT_COMMIT_BY_ME -e INPUT_SHOW_PROFILE_VIEWS -e INPUT_SHOW_SHORT_INFO -e INPUT_IGNORED_REPOS -e INPUT_COMMIT_MESSAGE -e INPUT_SHOW_UPDATED_DATE -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/dionnenoellabarretto/dionnenoellabarretto":"/github/workspace" f88420:45d1aeaba05d43d99d460f8304578bf5
Traceback (most recent call last):
File "/main.py", line 525, in
repo.update_file(path=contents.path, message=commit_message,
File "/usr/local/lib/python3.8/site-packages/github/Repository.py", line 2121, in update_file
headers, data = self._requester.requestJsonAndCheck(
File "/usr/local/lib/python3.8/site-packages/github/Requester.py", line 315, in requestJsonAndCheck
return self.__check(
File "/usr/local/lib/python3.8/site-packages/github/Requester.py", line 340, in __check
raise self.__createException(status, responseHeaders, output)
github.GithubException.GithubException: 422 {"message": "Validation Failed", "errors": [{"resource": "committer", "code": "missing_field", "field": "email"}], "documentation_url": "https://docs.github.com/rest/reference/repos#create-or-update-file-contents"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/main.py", line 529, in
repo.update_file(path=contents.path, message=commit_message,
File "/usr/local/lib/python3.8/site-packages/github/Repository.py", line 2121, in update_file
headers, data = self._requester.requestJsonAndCheck(
File "/usr/local/lib/python3.8/site-packages/github/Requester.py", line 315, in requestJsonAndCheck
return self.__check(
File "/usr/local/lib/python3.8/site-packages/github/Requester.py", line 340, in __check
raise self.__createException(status, responseHeaders, output)
github.GithubException.GithubException: 422 {"message": "Validation Failed", "errors": [{"resource": "committer", "code": "missing_field", "field": "email"}], "documentation_url": "https://docs.github.com/rest/reference/repos#create-or-update-file-contents"}
Username DionneNoellaBarretto
Cannot find the Locale choosing default to english
Exception Occurred 422 {"message": "Validation Failed", "errors": [{"resource": "committer", "code": "missing_field", "field": "email"}], "documentation_url": "https://docs.github.com/rest/reference/repos#create-or-update-file-contents"}`

**Comment by oHTGo** [comment]
Hi,
I just checked your workflows in your profile, saw a LOCALE value in the main.yml file and its type was "True" when actually the value needed was a string value, for example "en", "fr" ",...

**Comment by DionneNoellaBarretto** [comment]
> Hi, After about 30 minutes of testing, I realized there are some problems in the PyGithub library as you said. There is a temporary fix is to set the COMMIT_BY_ME flag to "False" to make it run normally. Not sure if this could be of any help to you?

@oHTGo  thank you so much for the workaround tip... Setting that to false sure did the trick for now.. :')

**Comment by oHTGo** [comment]
@DionneNoellaBarretto after I debug, I found out that the bug is not caused by PyGithub but can't get my email using GraphQL, must use through API
@anmol098 I made a pull request to fix this bug, hope to be accepted

**Comment by anmol098** [comment]
Email can be obtained from API as well as from GraphQL 
provided that when generating the GitHub token that should be granted following scope  ['user: email', 'read: user']
