### ISSUE TITLE
BUG: [ERROR] wakatime-core exited with status: 3221225477

### ISSUE THREAD

**Issue by BigProject404** [anmol098/waka-readme-stats#237]
**Describe the bug**
Stats do not send to waka. `[WakaTime] [ERROR] wakatime-core exited with status: 3221225477` message appeared in my editor console (sublime text). I haven't found anything on the Net about this error (I tried)

**To Reproduce**
I really don't know what happened. My api-key is correct.

**Comment by anmol098** [comment]
this error you reported seems to be from Wakatime extension for sublime
this might not be the correct change to report this issue please report to wakatime
