### ISSUE TITLE
[BUG] Resource not accessible by integration

### ISSUE THREAD

**Issue by iquasere** [anmol098/waka-readme-stats#242]
Greetings! I am trying to use this tool for the first time, but have not managed to get it working.
wakatime succeeds in GitHub action but does not write to README.
In the [workflow run](https://github.com/iquasere/iquasere/runs/4409045863?check_suite_focus=true), go to the "Run anmol98..." step. There, it reports:
```
Traceback (most recent call last):
  File "/main.py", line 536, in <module>
    emails_user = run_v3_api("/user/emails")  # Execute the api
  File "/main.py", line 107, in run_v3_api
    raise Exception(
Exception: Query failed to run by returning code of 403. /user/emails,... {'message': 'Resource not accessible by integration', 'documentation_url': 'https://docs.github.com/rest/reference/users#list-email-addresses-for-the-authenticated-user'}
Exception Occurred Query failed to run by returning code of 403. /user/emails,... {'message': 'Resource not accessible by integration', 'documentation_url': 'https://docs.github.com/rest/reference/users#list-email-addresses-for-the-authenticated-user'}
```
Is this because one of my secrets is wrongly configurated? In the yaml, I only use the waka API key, the one I submitted in Pycharm.
```
name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '5 * * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
```

**Comment by anmol098** [comment]
Can you please check you github auth token..
That is invalid or does not have sufficient privileges

**Comment by anmol098** [comment]
This issue is irrelevant
You can try the steps listed on Readme file.
It will get you working

**Comment by iquasere** [comment]
Turns out I hadn't yet authorized the application in GitHub! Thanks for an amazing tool!
