### ISSUE TITLE
request always reset by peer

### ISSUE THREAD

**Issue by ronething** [anmol098/waka-readme-stats#258]
**Describe the bug**

request always reset by peer

https://github.com/ronething/ronething/runs/4908450116?check_suite_focus=true

![image](https://user-images.githubusercontent.com/28869910/150662318-807be35f-0b6a-4556-a60e-a567378b956d.png)

https://github.com/anmol098/waka-readme-stats/blob/master/main.py#L432

**To Reproduce**

run actions

**Expected behavior**

may be request another link or request error then support retry?

**Github repository link**

https://github.com/ronething/ronething/actions

**Additional context**

thx

**Comment by anmol098** [comment]
I can see your profile is updated and the last run was also executed successfully
A connection reset by peer message means that the site you are connected to has reset the connection. This is usually caused by a high amount of traffic on the site, but may be caused by a server error as well.

**Comment by ronething** [comment]
yeah, i manually run the actions and it is success,
then i also change the cron time to avoid the high amount of traffic on the site

**Comment by 1interceptor3** [comment]
I have a similar problem. The api is opened locally. Starting the workflow manually doesn't help.
