### ISSUE TITLE
BUG : Exception Occurred invalid key 'data' keyError

### ISSUE THREAD

**Issue by akgupta0777** [anmol098/waka-readme-stats#260]
**Describe the bug**
So I configured my github action to github stats on my readme but they are not showing. So I dig deeper and found this message in log.

![image](https://user-images.githubusercontent.com/51379307/150836612-ad080a6c-0c67-46d8-b85e-2e9492714730.png)

**Expected behavior**
It should show all stats properly.

**Github repository link**
https://github.com/akgupta0777/akgupta0777

**Additional context**
I used the USERNAME in my action yml file seems optional but still I added it. Is USERNAME deprecated ?

**Comment by miermontoto** [comment]
make sure to add `read:user` and `user:email ` to the permissions of the token you're using.

**Comment by akgupta0777** [comment]
I guess I haven't give token that permission. I will update you.

**Comment by akgupta0777** [comment]
It worked !! but don't you think its kinda slow takes 5 mins. 
And also in docs it should be documented that these permissions should be enabled. If you think so I will happy to send a PR :-)

**Comment by anmol098** [comment]
@akgupta0777 it's mentioned on doc the user and repo scope is required for the token. you can improve the docs if you didn't find the docs clear
yes it takes time to process the whole data. because we can spam GitHub API at once so a wait timer is added.
