### ISSUE TITLE
BUG Exception Occurred Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by nasyxx** [anmol098/waka-readme-stats#27]
Did I set it up correctly?

The action log here: https://github.com/nasyxx/nasyxx/runs/936386840?check_suite_focus=true

And my workflow here: https://github.com/nasyxx/nasyxx/blob/master/.github/workflows/wakatime.yml

**Comment by Corfucinas** [comment]
I got a similar error just now

https://github.com/Corfucinas/Corfucinas/runs/936907240?check_suite_focus=true

**Comment by Corfucinas** [comment]
Ok, I got exactly the same error as you @nasyxx 

https://github.com/Corfucinas/Corfucinas/runs/936917368

**Comment by anmol098** [comment]
hey @Corfucinas and @nasyxx can you please re-run the workflow as the exception was not very clear so I added the traceback to look more into the error......

**Comment by Corfucinas** [comment]
@anmol098 

Here you go

https://github.com/Corfucinas/Corfucinas/runs/936975437?check_suite_focus=true

Seems this is what's causing it

`
File "/loc.py", line 42, in run_query_v3
    return request.json()
`

**Comment by anmol098** [comment]
@Corfucinas thank you for sharing this. I am looking in to this issue and will be pushing the fix as soon as possible

**Comment by Corfucinas** [comment]
@anmol098 sure thing!

Try to step-into using the debugger and see what is that object...could be an encoding problem or the `request` is returning something else.

**Comment by anmol098** [comment]
hey @Corfucinas and @nasyxx ... I pushed the patched which fixes the problem.
the root cause of the error was due to an empty repository in your account which was causing the program to throw an exception.
I fixed the issue you can check that...if the issue still persists feel free to open the issue again.

**Comment by Corfucinas** [comment]
Great!

Ill also take a look into that, thanks for patching it

**Comment by nasyxx** [comment]
Thanks!
