### ISSUE TITLE
BUG: empty block for " 📊 This Week I Spent My Time On"

### ISSUE THREAD

**Issue by Koushikphy** [anmol098/waka-readme-stats#270]
I have 
```
          SHOW_OS: "False"
          SHOW_PROJECTS: "False"
          SHOW_EDITORS: "False"
          SHOW_LANGUAGE: "False"
          SHOW_TIMEZONE: "False"
```
But still a empty "📊 This Week I Spent My Time On" block is shown. It should not be present there.  
Repo link https://github.com/Koushikphy/Koushikphy

**Comment by aravindvnair99** [comment]
Hey @Koushikphy!

Quoting https://github.com/Koushikphy/Koushikphy/runs/5525536927?check_suite_focus=true#step:4:25

> User stats are calculating. Try again later.

**Comment by Koushikphy** [comment]
So, how do I know when it will work properly?

**Comment by aravindvnair99** [comment]
> So, how do I know when it will work properly?

You can wait for WakaTime to process your profile. You'll see it in your dashboard. Once it's processed, try running the workflow again and you should be able to see the details.

**Comment by Koushikphy** [comment]
I don't see anything in my wakatime dashboard that is "being processed". I can query the API `https://wakatime.com/api/v1/users/current/` from browser and it always returns proper data.

**Comment by AlfinIndrawan** [comment]
@Koushikphy  any progress to disable that block?
