### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by SSIvanov19** [anmol098/waka-readme-stats#271]
**Describe the bug**
When I run the action, I get the following error:
![image](https://user-images.githubusercontent.com/63718744/158073137-053af4b4-97b7-4d36-a5fb-4b093fa0068b.png)

**To Reproduce**
1. Run the action
2. See the error

**Expected behavior**
The action to run without any errors.

**Github repository link**
[Repo](https://github.com/SSIvanov19/ssivanov19)

**Additional context**
[Link to the action](https://github.com/SSIvanov19/ssivanov19/runs/5529021041?check_suite_focus=true)

**Comment by oHTGo** [comment]
![image](https://user-images.githubusercontent.com/69106844/158328392-ddca1eef-27b4-45f1-92e9-dfa9a0d665bc.png)
Have you tried giving the access token enough permissions?

**Comment by SSIvanov19** [comment]
Thanks for the reply!

It turned out that the token didn't have authorization for my school organisation. Now everything is working. Thanks for helping with the problem!
