### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by pr2tik1** [anmol098/waka-readme-stats#28]
**Describe the bug**
The spacing between Language is uneven for the case of "Jupyter Notebook" (Github detects it as Language though it's not.)

![Screenshot from 2020-08-01 22-36-25](https://user-images.githubusercontent.com/34391513/89115871-e7ff0480-d4aa-11ea-9622-021bebf71c24.png)

**To Reproduce**
1. Go to https://github.com/pr2tik1/pr2tik1
2. View the section

**Comment by anmol098** [comment]
@pr2tik1 thank you for pointing this issue.... We will fix this soon in next update...

**Comment by anmol098** [comment]
@pr2tik1 can you please verify this. I tried to fix this in last commit

**Comment by pr2tik1** [comment]
Hi @anmol098 , sure, I have updated the yml file with:

```
 SHOW_LANGUAGE_PER_REPO: "True"
```
also I have re-run the past job from github actions, but there is no changes shown. I have a doubt regarding job schedule, what should I set it to for testing purpose? Is rerunning the last update action correct way of testing your new update?

**Comment by anmol098** [comment]
I proposed a pull request [#1](https://github.com/pr2tik1/pr2tik1/pull/1)
now in action tab select the action name there you will get the option to trigger the action

**Comment by pr2tik1** [comment]
it works! thanks! great work! 🙌🙌🙌
