### ISSUE TITLE
Remove "📊 This week I spent my time on" when empty

### ISSUE THREAD

**Issue by angristan** [anmol098/waka-readme-stats#30]
I'm only using `SHOW_COMMIT` so the next section is empty:

![image](https://user-images.githubusercontent.com/11699655/89122723-ff011f00-d4c9-11ea-9aaf-9335e10e4daa.png)

It would be nice to not show it when it's empty 🙂 

My env is:

```yml
SHOW_DAYS_OF_WEEK: False
SHOW_EDITORS: False
SHOW_LANGUAGE_PER_REPO: False
SHOW_LANGUAGE: False
SHOW_LOC_CHART: False
SHOW_OS: False
SHOW_PROJECTS: False
SHOW_TIMEZONE: False
SHOW_LINES_OF_CODE: False
```

**Comment by anmol098** [comment]
@angristan this is fixed you can check and inform the same

**Comment by Trysupe** [comment]
@angristan did the commit from @anmol098 on 04 Aug 2020 fix it for you? I have the same [issue](https://github.com/anmol098/waka-readme-stats/issues/156).

**Comment by angristan** [comment]
@Trysupe I don't use this anymore, sorry!
