### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by lucaspinarj** [anmol098/waka-readme-stats#301]
**Describe the bug**
Simply I can't make the time i spent in 'x' language to appear... I've already checked the WakaTime API key, everything looks fine, neither the languages that I use nor the OS is being identified.

**To Reproduce**
It's just not working properly and I can't figure it out why, I've made thousands of commits with different flags, I've already recreated the workflow, changed the API key or created another secret repository.

**Expected behavior**
<img width="536" alt="Captura de Tela 2022-07-09 às 00 09 56" src="https://user-images.githubusercontent.com/81657425/178089441-1c0d03b2-26a0-4ea3-b104-5f9aed9d5d5b.png">
I just wanted the info to be shown, but it seems like it's coded different idk...
**Github repository link**
https://github.com/lucaspinarj/lucaspinarj.git

**Additional context**
<img width="876" alt="Captura de Tela 2022-07-09 às 00 06 28" src="https://user-images.githubusercontent.com/81657425/178089486-3f4dae5e-8da8-44b5-bcd9-a3fc85b4a302.png">
I have turned off some features, the one and only that doesn't work properly is the "THIS WEEK I SPENT MY TIME ON" anything else is working fine.

**Comment by anmol098** [comment]
As you mentioned you have checked Waka time api..
Can you share the api response here so that we can debug and add missing
things.

**Comment by lucaspinarj** [comment]
I'm sorry, I'm kind of new on github, how may I do that?

**Comment by lucaspinarj** [comment]
Ok, for some reason that I couldn't find out the workflow ran automatically and it worked normally, the manual runs weren't giving any results idk why this happened, but I think it's fixed.

**Comment by ArslanAmeer** [comment]
@lucaspinarj  Yes manually trigger will not update README.md file

**Comment by lucaspinarj** [comment]
@ArslanAmeer that was not the point lol. Some features were missing and they suddenly came back.
