### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by DevTaehong** [anmol098/waka-readme-stats#305]
**Describe the bug**
I followed all instruction and when I run the action, I got this exception that
Traceback (most recent call last):
  File "/main.py", line 547, in <module>
    user_data = run_query(userInfoQuery)  # Execute the query
  File "/main.py", line 173, in run_query
    raise Exception("Query failed to run by returning code of {}. {}".format(request.status_code, query))
Exception: Query failed to run by returning code of 401. 
{
    viewer {
      login
      email
      id
    }
  }

I expected that I would work but It is not working

**Github repository link**
https://github.com/DevTaehong/DevTaehong

Thank you.

**Comment by ArslanAmeer** [comment]
@DevTaehong :

1: You need to update your GitHub Personal Access token, regenerate new one add it `Gh_TOKEN` in waka workflow file or in your repo secret.
2: Remove all the content written in between the waka tags and save.
3: It will take some time (in my case, a few hours) to run and update your README. Please note: manual trigger workflow will not update the README file

**Comment by DevTaehong** [comment]
@ArslanAmeer 
I regenerated my personal Access token and added it but it is not still working.

**Comment by DevTaehong** [comment]
@ArslanAmeer 
Thank you, man!
I was wrong. I should have added GH_TOKEN in my repo secret.
