### ISSUE TITLE
BUG: stats not generate due to 202 accepted

### ISSUE THREAD

**Issue by yanyongyu** [anmol098/waka-readme-stats#316]
**Describe the bug**

Wakatime's stats api may return response with 202 accepted status code. In this case, the response data is not completed and the action may raise a KeyError for missing data.

> [202 - Accepted](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/202): The request has been accepted for processing, but the processing has not been completed. The [stats resource](https://wakatime.com/developers#stats) may return this code.

**To Reproduce**

- Run the action.
- Wakatime cannot return the result immediately (Processing).
- action receives 202 accepted response with incompleted data (with a `percent_calculated` field in data).
- action failed

**Expected behavior**

Handle the 202 response correctly. (e.g. retry?)

**Github repository link**

https://github.com/yanyongyu/yanyongyu

**Comment by anmol098** [comment]
FIXED in #306
