### ISSUE TITLE
Provide ability to remove or replace the header texts

### ISSUE THREAD

**Issue by manastalukdar** [anmol098/waka-readme-stats#35]
Please provide ability to remove or replace the header texts, such as `I mostly code in JavaScript`, `📅 I'm Most Productive on Saturdays`, etc.

**Comment by anmol098** [comment]
@manastalukdar can you please elaborate itore.. Because all these values are automatically computed and modifying the title i will have to create more flags for the same.... That will be unnecessary no one will take pain to do this...... We are thinking other way round to do this......... If you have any suggestions on how to approach you can also give your suggestions.

**Comment by manastalukdar** [comment]
I imagine there is a static and a dynamic / computed part to the string. For example considering `I mostly code in JavaScript`:

- Static part: `I mostly code in `.
- Dynamic part: `JavaScript`.

My suggestion would be to provide 2 options (in decreasing order of priority):

1. Option 1: Replace title. Let user completely replace the string with something s/he would specify. So user specified fully static string.
2. Option 2: Remove title. This will complete remove the header string.

A stretch goal could be a third option: Let user provide text to replace only the static portion of the string.

If it help, this request came about from the header, `I mostly code in JavaScript`. It seems this is based on the first ranked of "language per repo". Keep in mind that someone may have 10 JS repos, but their contributions in JS may be 5% of all their contributions. At the very least, consider changing this header text to something along the lines of: `My top ranked language by repositories count is JavaScript.`

**Comment by anmol098** [comment]
I got your point.... That thing I can work on like completely removing headings....but making heading dynamic is not much of use-case... Like it will increase the user-onboarding time and that we don't want to.... We want the on-boaring to be sweet and simple...
