### ISSUE TITLE
Repository inactivity

### ISSUE THREAD

**Issue by pseusys** [anmol098/waka-readme-stats#351]
Dear @anmol098, @aravindvnair99 and any other project team member to stumble upon this issue!

I've been using your awesome action for just about a year now and I loved it - it really made my profile look much better every day.  
However, I couldn't help but notice that right now the project is not in its golden age: pull requests are neither getting merged nor reviewd, issues are left without any attention, etc.

Furthermore, right now (and it's already for about 2 or 3 month) a critical bug has literally broke this action. It doesn't work anymore. I've proposed a solution to the problem, but got no answer and no attention. Smell of abandonment is in the air.

Just get me right, I'm not blaming anyone, you've done a perfect work I've used and liked, I appreciate your efforts a lot. But if you don't have any spare time to support this project now (or for now), maybe you could've considered transferring this repository to anyone willing to contribute and support it or adding some more members to your team? I could've helped you if I became a collaborator, for example.

__If you can't use this awesome project right now just like me__, I'm inviting you to my [fork](https://github.com/pseusys/waka-readme-stats). If the situation's not getting better for some time, maybe we should consider adding it to market? Let me know if I can help!

I just want my readme to look as good as it used to as well as to help anyone who shares my will.

**Comment by aravindvnair99** [comment]
Hi @pseusys!

Thank you for reaching out to us! @anmol098 is the owner of this project and I'm a collaborator. I used to pitch in wherever I could as I got time on my hands.

During my BTech days I did have time to spare whenever I wasn't working part-time or freelancing but I work full-time now and have limited time to spare as my priorities have changed.

But with that said, I do read the emails I receive and do reply here. I have reviewed issues and pull requests a few times as well as I got time.

However, I agree that if there's someone who's interested in being a collaborator and has time to spare, then he or she could pitch in and be added to the team to take this project forward.

Let's wait to hear from @anmol098 as he works full-time too and has his own priorities to take care of.

**Comment by pseusys** [comment]
I have some time (from time to time) and could've helped you in your efforts on the projest.

**Comment by aravindvnair99** [comment]
Thanks @pseusys! I've merged your PR #346

**Comment by pseusys** [comment]
Thanks, @aravindvnair99, I appreciate that!

**Comment by anmol098** [comment]
Hi @pseusys
Really appreciate your effort for reviewing the bug and submitting the PR.
Due other priorities I am not able to actively maintain this project I'll add you as a collaborator if you are willing to collaborate and maintain the project going forward that will be very helpful 😊

**Comment by anmol098** [comment]
@aravindvnair99 appreciate your effort also. For making out the time to review PRs and approving them 👏

**Comment by MarkenJaden** [comment]
Hello together,
I would also volunteer to maintain the repository. I've been using it for a long time and added a small timestamp at the end of the readme a while ago.

If you say you don't want to get too many people on board, that's no problem, I won't fight for it, I'm also a full time employee, so time can be quite short here and there. Just want to support you here and there :)

**Comment by aravindvnair99** [comment]
Thanks for your interest @MarkenJaden! You've been added to this repository. Looking forward to your contribution!
