### ISSUE TITLE
Wrong commits count

### ISSUE THREAD

**Issue by nowiwr01w** [anmol098/waka-readme-stats#366]
I use waka-readme-stats since Jan 2023 and now it seems it has a problem with commits count
I have 530+ contributions (commits, prs, reviews, etc), but it shows only 122 commits in both fields (I'm an Early & I'm Most Productive on)

You can check it here: https://github.com/nowiwr01w/nowiwr01w

Can you please say mb I missed something?
Thanks

**Comment by nowiwr01w** [comment]
Okay, thank you for info
But the issue about commits count. PRs and reviews are the small part of my contributions
I have a "Meetings" project with 561 commits. I started this project at the end of december, so I guess 4/5 of these commits should be seen with waka-readme-stats, but it's not

**Comment by nowiwr01w** [comment]
So if I have 500 commits in main branch, it will show only 100 in statistic and if I want to get more commits in statistic, I should use another branch?

**Comment by nowiwr01w** [comment]
Okay, thank you <3

**Comment by muskan152001** [comment]
That’s how it works right now, but I hope the PR adding pagination support gets merged soon—it should fix this behavior.
