### ISSUE TITLE
BUG I think..

### ISSUE THREAD

**Issue by moonrope** [anmol098/waka-readme-stats#37]
**Describe the bug**
I had follow all the steps, add my secret keys, add the text in the readme, run the action, but I run manually the action, and nothing happens, the action is been run and completed but I can't see the stats.
Please help.

**To Reproduce**
Follow the instructions of the readme

**Expected behavior**
Show the results in my readme

**Github repository link**
anmol098/waka-readme-stats@master

**Additional context**
Maybe I'm missing somthing...

**Comment by moonrope** [comment]
Okey I check it is not a bug, in the documentation it says that should be anmol098/waka-readme-stats@master but I tried with anmol098/waka-readme-stats@V1.1 and it works like charm, I add a pull request to change the documentation to the new version #38

**Comment by anmol098** [comment]
anmol098/waka-readme-stats@master
Worked for everyone.. None of issue have been raised till now.. Please recheck your action workflow file.. And give the error message is possible...
