### ISSUE TITLE
Enable GitHub features

### ISSUE THREAD

**Issue by aravindvnair99** [anmol098/waka-readme-stats#389]
Hi @anmol098!

Can you enable the following?

- Enable secret scanning in https://github.com/anmol098/waka-readme-stats/security/secret-scanning
- Enable all in https://github.com/anmol098/waka-readme-stats/settings/security_analysis
- In https://github.com/anmol098/waka-readme-stats/settings/branches for `master` branch:
    - Enable `Require a pull request before merging`
    - Set `Require approvals` to `1`
    - Enable `Dismiss stale pull request approvals when new commits are pushed`
    - Enable `Require approval of the most recent reviewable push`
    - Enable `Require status checks to pass before merging`
    - Enable `Require branches to be up to date before merging` and add our GitHub Actions workflows as required.
    - Enable `Require conversation resolution before merging`
- In https://github.com/anmol098/waka-readme-stats/settings
    - Enable `Always suggest updating pull request branches`
    - Enable `Automatically delete head branches`

**Comment by anmol098** [comment]
hi @aravindvnair99 requested changes done
