### ISSUE TITLE
Anmol's wakatime stats

### ISSUE THREAD

**Issue by pseusys** [anmol098/waka-readme-stats#406]
**Describe the bug**
Something seems to be wrong with @anmol098's wakatime stats.
If you take a look at any of the recent PRs, the section `This Week I Spent My Time On` contains strange information; all entries there are equal to 0.
Maybe it's worth taking a look at wakatime dashboard, there's no error happening - meaning that the invalid data comes directly from WakaTime.

**Comment by anmol098** [comment]
This seems to be the bug from Waka time on dashboard also I can see 0.
This happens when you open a IDE and didn't spend 1min and before that you close the IDE so a heartbeat is registered on server with 0min
