### ISSUE TITLE
@anmol098 could you confirm if you see an option to switch to advanced?

### ISSUE THREAD

**Issue by aravindvnair99** [anmol098/waka-readme-stats#407]
@anmol098 could you confirm if you see an option to switch to advanced?

Quoting https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/troubleshooting-the-codeql-workflow#results-are-different-than-expected :

```
To check if default setup is enabled, navigate to the main page of the repository, then click  Settings. In the "Security" section of the sidebar, click  Code security and analysis. In the "Code scanning" section of the page, next to "CodeQL analysis," click . If there is a  Switch to advanced option, you are currently using the default setup. To switch to the advanced setup and get code scanning results from your custom workflow file, click  Disable CodeQL. This option will only disable default setup, and your pre-existing workflow will start uploading results again.
```

_Originally posted by @aravindvnair99 in https://github.com/anmol098/waka-readme-stats/issues/387#issuecomment-1445353011_

**Comment by anmol098** [comment]
@aravindvnair99 yes there's the option for advanced scanning.. Do you want it to be enabled?

**Comment by aravindvnair99** [comment]
@anmol098 yes, please enable it.

**Comment by aravindvnair99** [comment]
@anmol098 could you confirm if you've enabled it?

**Comment by anmol098** [comment]
i have enabled it asked me to commit a codeql file pl check #416

**Comment by aravindvnair99** [comment]
Thanks!
