### ISSUE TITLE
TypeError: '>' not supported between instances of 'NoneType' and 'int' - BUG

### ISSUE THREAD

**Issue by Corfucinas** [anmol098/waka-readme-stats#41]
Hi,

I just came across the following bug when running the action.

https://github.com/Corfucinas/Corfucinas/runs/944933598?check_suite_focus=true

**Comment by anmol098** [comment]
@hedythedev please look into this as this thing was update by you.

**Comment by anmol098** [comment]
@Corfucinas the issue is fixed with the latest push you can check and inform the same

**Comment by Corfucinas** [comment]
@anmol098 

Seems that it's working fin, cronjob just activated
