### ISSUE TITLE
BUG: GitHub stats not printing

### ISSUE THREAD

**Issue by HasanIhsan** [anmol098/waka-readme-stats#432]
Github Stats are not printing out! my stats from wakatime print out normally(at least i think they do) but i don't get anything when it comes to GitHub (and the workflow runs without error. 

![image](https://user-images.githubusercontent.com/49534968/225942389-856900bf-a237-43a6-8d39-4e204b5d127b.png)

**my workflow file**
![image](https://user-images.githubusercontent.com/49534968/225941949-a7ee3ed8-062b-4873-be74-68e5ae7f538c.png)

**Comment by vonhyou** [comment]
same issue

**Comment by NONPLAYT** [comment]
same

**Comment by thenithinbalaji** [comment]
I am also facing the same issue

**Comment by mayraamaral** [comment]
same issue

**Comment by anmol098** [comment]
@pseusys i think it's not about flag setting to True / False.
it's seems like some calculation is broken when calculating day wise and week wise for both section it shows 0 commits.
and i visited users profile previously the tool has printed commits for day wise and week wise. we have to check how we are calculating the stats from github

**Comment by anmol098** [comment]
For the users affected by #427 for them the tool is not calculating the Github commit stats
we deployed the fix #428 seems like we have to re-address the fix again 

CC @pseusys @aravindvnair99 @AndPuQing

**Comment by anmol098** [comment]
@pseusys i found the bug when `SHOW_LINES_OF_CODE` and `SHOW_LOC_CHART` both flags are set to false the tool is not calculating the github stats.

for all the users who have set these both flags to false will experience the same issue for them weekly and daily commit data will be printed to 0
