### ISSUE TITLE
how to delete [📊 This Week I Spent My Time On]?

### ISSUE THREAD

**Issue by stewForAni** [anmol098/waka-readme-stats#453]
hi bro :
how to delete [📊 This Week I Spent My Time On] this section ?

**Comment by txtxj** [comment]
This section is not displayed when all of the following options are turned off.

https://github.com/anmol098/waka-readme-stats/blob/f8cec5f73e6f2a551a25da883d849b06f471a918/sources/main.py#L38

Of these, only the `SHOW_OS` option defaults to False.

**Comment by stewForAni** [comment]
> This section is not displayed when all of the following options are turned off.
> 
> https://github.com/anmol098/waka-readme-stats/blob/f8cec5f73e6f2a551a25da883d849b06f471a918/sources/main.py#L38-L40
> 
> Of these, only the `SHOW_OS` option defaults to False.


> This section is not displayed when all of the following options are turned off.
> 
> https://github.com/anmol098/waka-readme-stats/blob/f8cec5f73e6f2a551a25da883d849b06f471a918/sources/main.py#L38-L40
> 
> Of these, only the `SHOW_OS` option defaults to False.

**Comment by stewForAni** [comment]
THANK YOU BRO
