### ISSUE TITLE
Cannot get the stats to be displayed on my Repo Page

### ISSUE THREAD

**Issue by olijeffers0n** [anmol098/waka-readme-stats#461]
**Describe the bug**
The action completes successfully but the stats are not displayed on the README

**To Reproduce**
Go to 'https://github.com/olijeffers0n/Test'
See the data is not populated but I believe it is configured correctly and the actions are succeeding 

**Expected behavior**
The data to be committed to the README

**Github repository link**
https://github.com/olijeffers0n/Test

**Comment by willnaoosmith** [comment]
Repository doesn't exists anymore
