### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by orhanarifoglu** [anmol098/waka-readme-stats#47]
Hi i cannot get actions to be triggered automatically every 12:00. My repo is here. What could it be the issue? Is my github actions yml file right? Thanks.

https://github.com/orhanarifoglu/orhanarifoglu

**Comment by orhanarifoglu** [comment]
Changed title

**Comment by orhanarifoglu** [comment]
Changed title

**Comment by anmol098** [comment]
referenced a pull request please check and merge 
[2](https://github.com/orhanarifoglu/orhanarifoglu/pull/2)
