### ISSUE TITLE
FEAT: commits made by bot

### ISSUE THREAD

**Issue by ajmeese7** [anmol098/waka-readme-stats#49]
**Is your feature request related to a problem? Please describe.**
With the [github-activity](https://github.com/jamesgeorge007/github-activity-readme) repo, the commits to your README are made by a GitHub bot. This means the commits aren't attributed to you, so they don't fill up your commit graph.

It would be awesome if this project could do something similar, so my chart is only populated by commits I actually make instead of loads of filler commits.

**Describe the solution you'd like**
An implementation of a GitHub bot that makes the commits on our behalf.

**Describe alternatives you've considered**
I can't think of any for this issue.

**Additional context**
![Example](https://user-images.githubusercontent.com/17814535/89735463-44709f80-da28-11ea-91ea-32d00d7f200d.png)

This is an example of commits made by the activity repo vs. the waka-readme-stats repo.

**Comment by anmol098** [comment]
@ajmeese7  As far as I understand... You want that commit made by Aur action should be on the behalf of the bot not your username?

**Comment by ajmeese7** [comment]
@anmol098 yes, exactly. I'd like the commits that show up on my commit chart to be valuable contributions I've made, so I don't have instances like this that overshadow my actual work:

![Commit Chart](https://user-images.githubusercontent.com/17814535/89735583-2fe0d700-da29-11ea-83d3-c6a0a06f740a.png)

**Comment by anmol098** [comment]
@ajmeese7 I got your point.. Since the stats which we are showing.. Basically requires the github personal access token to get that data from github api...
Ok I have accounted that... And will try to find the other way round to get over this...

**Comment by anmol098** [comment]
Pull request #51 from you fixes this issue....
