### ISSUE TITLE
FEAT: Three quarters? Why so?

### ISSUE THREAD

**Issue by Paveloom** [anmol098/waka-readme-stats#50]
I'm definitely missing something. I thought traditionally the year was divided into [four quarters](https://en.wikipedia.org/wiki/Calendar_year#Quarters), not three. So it's four months now? Is this some limitation on the API's part? Is it possible to remake it? It's a bit confusing.

**Comment by anmol098** [comment]
@prabhatdev please look at this and modify the changes
