### ISSUE TITLE
Align progress bars

### ISSUE THREAD

**Issue by guilyx** [anmol098/waka-readme-stats#6]
Hi, 

Here's the current state of my board :

```
🌞 Morning    261 commits    ████░░░░░░░░░░░░░░░░░░░░░   16.72% 
🌆 Daytime    638 commits    ██████████░░░░░░░░░░░░░░░   40.87% 
🌃 Evening    437 commits    ███████░░░░░░░░░░░░░░░░░░   27.99% 
🌙 Night      225 commits    ███░░░░░░░░░░░░░░░░░░░░░░   14.41%
```

```
💬 Languages: 
Go                       11 hrs 37 mins      █████████████░░░░░░░░░░░░   54.17% 
Bash                     5 hrs 44 mins       ██████░░░░░░░░░░░░░░░░░░░   26.76% 
Julia                    1 hr 22 mins        █░░░░░░░░░░░░░░░░░░░░░░░░   6.4% 
Other                    56 mins             █░░░░░░░░░░░░░░░░░░░░░░░░   4.4% 
Protocol Buffer          52 mins             █░░░░░░░░░░░░░░░░░░░░░░░░   4.05%
```

Wouldn't it be better if all progress bars were aligned both right and left ? This could be a simple fix I could look into ( it would take about a week for me to have the time to actually do it though )

**Comment by anmol098** [comment]
Thanks for highlighting the issue if you want you can look into it all suggestions are accepted. together we can make this a better Github action

**Comment by guilyx** [comment]
Actually @anmol098 :

- On Ubuntu 18.04, Firefox, it's not aligned
- On Windows 10, Opera, it's aligned

Might be a non-issue

**Comment by anmol098** [comment]
@guilyx can you please share the screnshot here of un-aligned stats on Firefox.

**Comment by guilyx** [comment]
![unaligned](https://user-images.githubusercontent.com/43545812/88273617-c0ee4900-ccda-11ea-9b88-128f258aee32.png)

**Comment by guilyx** [comment]
Black and Grey characters aren't the same size, unsure if it's firefox or ubuntu related

**Comment by anmol098** [comment]
@guilyx I think the issue is browser specific......
Because on dry run at console every character are equal...

**Comment by guilyx** [comment]
Indeed, Firefox only, you can close !

**Comment by anmol098** [comment]
@guilyx thank you very much... You suggestions and feature on this GitHub action is always welcomed
