### ISSUE TITLE
Just a Italian grammar fix

### ISSUE THREAD

**Issue by Tkd-Alex** [anmol098/waka-readme-stats#63]
https://github.com/anmol098/waka-readme-stats/blob/0c8b6e5f004a19b19dadb1be6832f23294d11fc1/translation.json#L99

@anmol098 
Can you please change "Sono piu' produttivo il", with **"Sono piu' produttivo di"**.
Italian grammar has many things to keep attention :smile_cat:

**Comment by anmol098** [comment]
ok will suerly fix this in next commit
