### ISSUE TITLE
What do you think about the 'Projects''s order?

### ISSUE THREAD

**Issue by Tkd-Alex** [anmol098/waka-readme-stats#64]
**Is your feature request related to a problem? Please describe.**
As you can see here in the README I've only 5 project listed, and this It's ok for me. 
But I work currently to other projects and I've spent more time than other project that are not listed below.

![image](https://user-images.githubusercontent.com/14061593/90374359-ab6b0580-e073-11ea-8a5a-07bcc3f61de2.png)

For example I've worked on mitmproxy-wsus more than Unknown Project.

![image](https://user-images.githubusercontent.com/14061593/90374489-dbb2a400-e073-11ea-9b35-8518b78db624.png)

**Describe the solution you'd like**
We can easly order the project by percentage, what do you think?
I can work on this PR if you think is a good idea.

**Comment by anmol098** [comment]
@Tkd-Alex thanks for being an active member sure you can work on this. i will also look at this
