### ISSUE TITLE
Lines removals in the graph

### ISSUE THREAD

**Issue by guilyx** [anmol098/waka-readme-stats#68]
Hey all,

In the graph section, it takes into account the number of lines input in github repositories.

I happen to have had some quarters where I removed more lines than added, making the graph go into negatives and disrupting the display a bit.

Few options : 
- count negative inputs as positive one and sum them up
- discredit entirely negative inputs
- adapt the graph for such cases

**Comment by anmol098** [comment]
@guilyx can you please verify the same as this was tried to be fixed in #72
