### ISSUE TITLE
Exception occured'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by bhanukaManesha** [anmol098/waka-readme-stats#8]
This is my dev metrics.
<img width="646" alt="Screenshot 2020-07-25 at 13 30 16" src="https://user-images.githubusercontent.com/30364196/88449641-06497c80-ce7b-11ea-9ccc-4e95720c36ee.png">

I'm new to WakaTime. I keep getting this error when I run the action.
Is it because my WakaTime account is new. Or is it some other bug?

<img width="337" alt="Screenshot 2020-07-25 at 13 31 35" src="https://user-images.githubusercontent.com/30364196/88449661-2d07b300-ce7b-11ea-807d-af2139402013.png">

**Comment by anmol098** [comment]
This is because... You don't have any metrics from Waka time... Once Waka time will record the metrics it will appear here...

**Comment by bhanukaManesha** [comment]
Okay. Thank you 👍
I will give it some time.
