### ISSUE TITLE
I'm getting an 401 error on run

### ISSUE THREAD

**Issue by Ayfri** [anmol098/waka-readme-stats#86]
**Describe the bug**
When running the workflow I get an error on the `run` step.

**To Reproduce**
1. Run the workflow.
2. Get this error :
```py
Traceback (most recent call last):
Exception Occurred Query failed to run by returning code of 401. 
  File "/main.py", line 491, in <module>
    user_data = run_query(userInfoQuery)  # Execute the query
  File "/main.py", line 152, in run_query
    raise Exception("Query failed to run by returning code of {}. {}".format(request.status_code, query))
Exception: Query failed to run by returning code of 401. 
{
    viewer {
      login
      id
    }
  }

{
    viewer {
      login
      id
    }
}
```

**Expected behavior**
Not getting an error and have statistics generated in the README.

**Github repository link**
https://github.com/Ayfri/Ayfri

**Comment by anmol098** [comment]
@Ayfri did you add the github personal access token with repo and user access to the secret? Because script is not able to authenticate to github with provided token..

**Comment by Ayfri** [comment]
Yes, I'll try with a token that have more permissions so.

**Comment by technologiespro** [comment]
0. **create access token** in profile settings > developer settings > personal access tokens > generate new token, set flags all repo, user, forget your secret key ghp_.... 
![g1](https://user-images.githubusercontent.com/9394904/181854182-47025700-aa1f-440c-b104-5bf9eb83d00f.png)

1. **open your repo** in git & click Settings ![g2](https://user-images.githubusercontent.com/9394904/181854312-c009c21b-eb32-4cf5-be07-8b138f0d7896.png)
2. **click on Secrets** > Actions & press New Repository secret ![g3](https://user-images.githubusercontent.com/9394904/181854745-2cffe760-2767-40ba-bfa1-4c79e100bc36.png)
3. **enter your gh**_.. secret and save
4. be glad you spent so little time solving this problem :)
