### ISSUE TITLE
BUG: "This Week I Spend My Time On" stats not reflecting stats for the whole week

### ISSUE THREAD

**Issue by betoma** [anmol098/waka-readme-stats#88]
**Describe the bug**
The action is running fine and updating as described. However, the "This Week I Spent My Time On" section is not reflecting the amount of time Wakatime has me as having worked for the past week -- whether you define it as the past seven days OR as the week starting with Sunday/Monday. For instance, the amount of time it claims I've worked on my "words-as-classifier" project is exactly equal to the amount I worked on that project _just yesterday_, and doesn't include any of the time I worked on that project even on Tuesday, much less for the rest of the week.
![chrome_HNaHlKfL1P](https://user-images.githubusercontent.com/32310072/91416663-00670280-e850-11ea-841b-b2522bf1bf66.png)
This time is definitely being logged within Wakatime, as evidenced by the following graph from Wakatime's website:
![chrome_ffvpfVttOC](https://user-images.githubusercontent.com/32310072/91416389-9c443e80-e84f-11ea-9b7d-62b2ebd145e8.png)
This is not unique to this particular project; the amount of time I worked on my 7a7aFaM project only reflects the amount of time I worked on that project on the 25th.

**To Reproduce**
It's unfortunately not clear to me what's causing this error, and I'm thus not really able to reproduce it as I haven't done anything other than the normal setup of the github action.

**Expected behavior**
I expected the "This Week I Spent My Time On" section to reflect the amount of work I'd done on various projects over the past 7 days in total.

**Github repository link**
https://github.com/betoma/betoma

**Additional context**

**Comment by anmol098** [comment]
@betoma these values are directly fetched from the waka-time api....
These values are printed untouched as we get from the Wakatime api... 
Possible issue can be the cron running time.... Because of difference in your timezone and the github server timezone.

**Comment by betoma** [comment]
@anmol098 yeah, after the most recent run of the action, the times are now up-to-date for the projects and languages that I didn't work on today -- it looks like it's most of my work from today that's missing. Is there a way to fix this by changing the chron time?

**Comment by anmol098** [comment]
@betoma I have seen your workflow file you are running stats at 18:30 UTC which is 00:00 IST
I saw your time zone is of Berlin
You should at cron at 22:00 UTC which will be 00:00 CEST
Or you should go for 00:00 UTC For cron choice is yours.
