### ISSUE TITLE
Most of the commits are in daytime/evening, still description shows night-owl.

### ISSUE THREAD

**Issue by tzmanish** [anmol098/waka-readme-stats#89]
![image](https://user-images.githubusercontent.com/20627358/91481903-cf73e580-e8c2-11ea-962a-b0cdbc3b4727.png)

**Comment by anmol098** [comment]
Ya... 
Night+evening = night 🦉.
And
Morning+ daytime = morning 🐦

**Comment by tzmanish** [comment]
Okay thanks
btw, what are the timeframes for morning, daytime, evening and night?

**Comment by anmol098** [comment]
@tzmanish 

morning is 6 - 12
    daytime is 12 - 18
    evening is 18 - 24
    night is 0 - 6
