### ISSUE TITLE
BUG: Query failed to run by returning code of 202

### ISSUE THREAD

**Issue by marcizhu** [anmol098/waka-readme-stats#91]
**Describe the bug**
I randomly get that message on some runs when I try to update my readme. When that happens, the amount of lines coded is not correct, so I need to manually re-run it and hope it doesn't fail once again.

**To Reproduce**
There's nothing I can do to reproduce it. As I said, it seems random. For example [this](https://github.com/marcizhu/marcizhu/runs/1050189251?check_suite_focus=true#step:3:20) run failed.

**Expected behavior**
It shouldn't print that message nor give invalid line counts.

**Github repository link**
https://github.com/marcizhu/marcizhu

**Comment by anmol098** [comment]
@marcizhu I am aware of this issue ...this is because sometimes the Github API fails to respond. due to consecutive API calls. or sometimes the GitHub repo is empty.
not able to find out the solution to this.

**Comment by marcizhu** [comment]
I'm unable to find a solution for this either. If I discover something, I'll let you know :D
