### ISSUE TITLE
feat: accept inclusion of organization accounts

### ISSUE THREAD

**Issue by matfax** [anmol098/waka-readme-stats#96]
**Is your feature request related to a problem? Please describe.**
Currently, this action doesn't include organization accounts. Only personal repositories seem to be tracked. This can make a big difference in the stats.

**Describe the solution you'd like**
An additional input could be added to the `action.yml` that is passed to the `LinesOfCode` class.

**Additional context**
[Here](https://medium.com/@tksukhu/get-your-github-organization-statistics-using-graphql-apollo-client-and-react-35839f580acf) is a nice blog post on this that uses the new v4 GraphQL API.

**Comment by anmol098** [comment]
@matfax this can be a nice addition but there is a catch until the organization gives permission to access their data we cannot do anything and no organization will allow some-one to access their repos other than the member of the organization
